# DO NOT CHANGE the "init" and "install" sections below

image: Visual Studio 2017

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

environment:
  global:
    GCC_PATH: mingw_64
    NOT_CRAN: true
    USE_RTOOLS: true

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 9dX5FdgTPlXuH7hBLKRLLPdBO+EpkMqNUYEvz62Rfuy8iDZoA+e8oB6GvBhh7SwIXeDsl1aXMCKDa6nN4W1pUnIdj//XhAMl4NNO82OcqFo=

